name: Go

on:
  workflow_dispatch:

env:
  GITHUB_NAME: pacoxu-bot
  GITHUB_EMAIL: paco2023@163.com
  STARED_NUMBER: 20

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My GitHub Status
        uses: ./
        with:
          WITH_STARED: false
          TELEGRAM_TOKEN: ${{ secrets.TELE_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
